name: Bundle/Release idTip.zip
on: [push]
jobs:
  Bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Make idTip directory
        run: mkdir idTip
      - name: Move all files to idTip directory
        run: mv *.toc idTip/ && mv clients/ idTip/ && mv lib/ idTip/ && mv libs/ idTip/
      - name: Zip idTip
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r idTip.zip idTip
      - name: Upload Release Package
        uses: actions/upload-artifact@v2
        with:
          name: idTip
          path: idTip.zip
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: idTip
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: idTip.zip
          asset_name: idTip.zip
          asset_content_type: application/zip
