name: Bundle/Release idTip.zip
on: [push]
jobs:
  Bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Make idTip directory
        run: mkdir idTip
      - name: Move all files to idTip directory
        run: mv *.toc idTip/ && mv clients/ idTip/ && mv lib/ idTip/ && mv libs/ idTip/
      - name: Zip idTip
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r idTip.zip idTip
      - name: Upload Release Package
        uses: actions/upload-artifact@v2
        with:
          name: idTip.zip
          path: idTip.zip
