name: Bundle/Release idTip.zip

on:
  push:
    branches:
      - main

jobs:
  Bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/checkout@v1
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{IDTIP_VERSION}}"
          replace: ${{ steps.semvers.outputs.patch }}
          regex: false
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ github.token }}
      - name: Make idTip directory
        run: mkdir idTip
      - name: Move all files to idTip directory
        run: mv *.toc idTip/ && mv clients/ idTip/ && mv lib/ idTip/ && mv libs/ idTip/
      - name: Zip idTip
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r idTip.zip idTip
      - name: Upload Release Package
        uses: actions/upload-artifact@v2
        with:
          name: idTip
          path: idTip
      - name: release
        uses: ncipollo/release-action@v1.11.1
        id: create_release
        with:
          tag: ${{ steps.semvers.outputs.patch }}
          name: idTip v${{ steps.semvers.outputs.patch }}
          body: ${{ steps.changelog.outputs.changelog }}
          artifacts: "idTip.zip"
        env:
          GITHUB_TOKEN: ${{ github.token }}
